

<div class="main-container col2-left-layout">	
	<div class="conten-home">	
		<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
		<div class="container-inner">
			<div class="producttab-conter">
				<?php echo $block->getLayout()->createBlock('Plazathemes\Producttab\Block\Producttab')->setTemplate('Plazathemes_Producttab::producttab.phtml')->toHtml();?>
			</div>	
		</div>
		
		<div class="static1">
			<div class="container-inner">
				<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static1_home3_home4')->toHtml(); ?>
			</div>
		</div>
		
		<div class="time-inner">
			<div class="container-inner">
				<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('Plazathemes_Pricecountdown::saleslider.phtml')->toHtml();?>
			</div>
		</div>
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static1_home1_home3')->toHtml(); ?>
		
		<div class="container-inner">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static_categor1_home3')->toHtml(); ?>
			
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static2_home3_home4')->toHtml(); ?>
		</div>

		<div class="container-inner">
			<div class="groud-blog">
				<div class="row">
					<div class="col-md-6 col-sm-12 col-xs-12">
						<?php echo $block->getLayout()->createBlock('Plazathemes\Randomproductslider\Block\Products')->setTemplate('Plazathemes_Randomproductslider::productslider.phtml')->toHtml();?>
					</div>
					<div class="col-md-6 col-sm-12 col-xs-12">
						<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
					</div>
				</div>
			</div>
			<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
		</div>	

	</div>

</div>


