<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
if($this->getConfig('enable_frontend')):
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	$image = 'category_page_grid';
	$_productHelper = $this->helper('Magento\Catalog\Helper\Product');
	$block = $this->getBlockProduct();
 
	$auto = $this->getConfig('auto');
	if($auto)
		$auto = 'true';
	else
		$auto = 'false';
	$rows = $this->getConfig('rows');
	$show_next_back = $this->getConfig('show_next_back');
	$pagination = $this->getConfig('pagination');
	if($this->getConfig('speed'))
		$speed = $this->getConfig('speed');
	else
		$speed = '3000';
	if($show_next_back)
		$show_next_back = 'true';
	else
		$show_next_back = 'false';
	$show_navigation_control = $this->getConfig('show_navigation_control');
	if($show_navigation_control)
		$show_navigation_control = 'true';
	else
		$show_navigation_control = 'false';
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$myHelper = $this->helper('Plazathemes\Themeoptions\Helper\Data');
?>
<div class="pt-randomproduct-container">
	<div class="row">
	<h2 class="ma-title"><span><?php echo $this->getConfig('title') ?></span></h2>
	<ul class="ptowl">
	<?php
	$i = 0;
	 foreach($this->getProducts() as $_product)
	{ 
			$productImage = $block->getImage($_product, $image);
		if($_product->getRotaryImage())
		$imageRotary = $myHelper->getMedia_Url().'catalog/product/'.$_product->getRotaryImage();
		else
		$imageRotary = '';       
	if($i%$rows == 0):
	?>
		<li class="item">
	<?php
	endif;
			$productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(800)->getUrl();
		?>
		
		<div class="item-inner">
			<div class="product-item-info">
				<div class="image-container ">
					<a href="<?php echo $_product->getProductUrl() ?>" class="product-item-photo">
						<img src="<?php echo $productImage; ?>" alt=""/>
						<span class="image-rotator">
							<?php if($imageRotary): ?>
							  <img src="<?php echo $imageRotary; ?>" alt="" />
							 <?php else: ?>
								<img src="<?php echo $productImage; ?>" alt=""/>
							 <?php endif; ?>
						</span>
					
					</a>
					<div class="box-hover">
						<div class="actions-primary">
									<?php if ($_product->isSaleable()): ?>
										<?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
											<button class="action tocart"
													data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_product) ?>"}}'
													type="button" title="<?php echo __('Add to Cart') ?>">
												<span><?php echo __('Add to Cart') ?></span>
											</button>
										<?php else: ?>
											<?php
												$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
												$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
											?>
											<button class="action tocart"
													data-post='<?php echo $postData; ?>'
													type="button" title="<?php echo __('Add to Cart') ?>">
												<span><?php echo __('Add to Cart') ?></span>
											</button>
										<?php endif; ?>
									<?php else: ?>
										<?php if ($_product->getIsSalable()): ?>
											<div class="stock available"><span><?php echo __('In stock') ?></span></div>
										<?php else: ?>
											<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
										<?php endif; ?>
									<?php endif; ?>
								</div>
								<div class="add-to-links" data-role="add-to-links">
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
										<a href="#"
										   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
										   class="action towishlist" data-action="add-to-wishlist"
										   title="<?php echo __('Add to Wishlist') ?>">
											<span><?php echo __('Wishlist') ?></span>
										</a>
									<?php endif; ?>
									<?php
									$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
									?>
									<a href="#"
									   class="action tocompare"
									   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
									   role="button">
										<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
									</a>
									
								</div>
					</div>
					
				</div>
				
				<div class="product-item-details">
					<div class="product-name">
						
						<strong class="product-item-name">
							<a href="<?php echo $_product->getProductUrl() ?>" class="product-item-link"><?php echo $_product->getName() ?></a>
						</strong>	
					</div>	
					<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
					<?php echo $block->getProductPrice($_product) ?>

					
				</div>
			</div>
		</div>
	<?php if($i%$rows == $rows - 1): ?>
		</li>
	<?php
	endif;
	$i++;
	}
	?>
	</ul>
</div>
</div>
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
		$(document).ready(function(){
			$(".pt-randomproduct-container .ptowl").owlCarousel({
				<?php
					if(($auto== 'true') && $speed):
				?>
				autoPlay : <?php echo $speed; ?>,
				<?php
					endif;
				?>
				items : 2,
				itemsDesktop : [1199,2],
				itemsDesktopSmall : [992,2],
				itemsTablet: [767,2],
				itemsMobile : [479,1],
				slideSpeed : <?php echo $pagination; ?>,
				paginationSpeed : <?php echo $pagination; ?>,
				rewindSpeed : <?php echo $pagination; ?>,
				addClassActive: true,
				navigation : <?php echo $show_next_back; ?>,
				stopOnHover : true,
				pagination : <?php echo $show_navigation_control; ?>,
				scrollPerPage:true,
			});
		});
	});
</script>
<?php
endif;
?>